# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development do
  gem "chandler", "0.9.0"
  gem "minitest", "5.20.0"
  gem "pry", "0.14.1"
  gem "rake", "13.0.6"
  gem "rake-compiler", "1.2.5"
  gem "simplecov", "0.21.2"
  gem "yard", "0.9.26"
end
